MIRROR/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.contrib.staticfiles.views import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='mirror_user/login/')),
    path('mirror_user/', include('apps.mirror_user.urls')),
    path('board/', include('apps.board.urls')),
    path('favicon.ico', serve, {'path': 'adminlte/dist/img/favicon.ico'}),

]

apps/board/urls.py
from django.urls import path,include
from django.views.generic import RedirectView
from . import views

app_name = "board"

urlpatterns = [
    path("<str:username>/", include([
        path('', RedirectView.as_view(url='projects/')),
        path("addproject/", views.board_addproject, name="addproject"),
        path("contact/", views.board_contact, name="contact"),
        path("docs/", views.board_docs, name="docs"),
        path("mainboard/<str:project_name>/", views.board_mainboard, name="mainboard"),
        path("projects/", views.board_projects, name="projects"),
        path("chart1/<str:project_name>/", views.board_chart1, name="chart1"),
        path("chart2/<str:project_name>/", views.board_chart2, name="chart2"),
        path("chart3/<str:project_name>/", views.board_chart3, name="chart3"),
        path("delete/<str:project_name>/", views.board_delete, name="delete"),
        path("table1/<str:project_name>/", views.board_table1, name="table1"),
        path("table2/<str:project_name>/", views.board_table2, name="table2"),
        path("settings/", views.board_settings, name="settings"),
        path("calendar/", views.board_calendar, name="calendar"),
    ]))
]

apps/board/models.py
from django.db import models
import django
from django.contrib.auth.models import User


# # Create your models here.
class Project(models.Model):

    users_participated = models.ManyToManyField(to=User, related_name='usersParticipated')

    project_id = models.CharField(max_length=50, null=True)
    # repository full name
    full_name = models.CharField(max_length=50, null=True)
    # repository description
    Description = models.CharField(max_length=100, null=True)
    # the date of when the repo was created
    Date_created = models.DateTimeField(default=django.utils.timezone.now, null=True)
    # the date of the last git push
    Date_of_lastpush = models.DateTimeField(default=django.utils.timezone.now, null=True)
    # programming language
    Language = models.CharField(max_length=50, null=True)
    # number of forks
    Number_of_forks = models.IntegerField(null=True)
    # number of stars
    Number_of_stars = models.IntegerField(null=True)
    # home page
    Home_page = models.CharField(max_length=50, null=True)
    # html url
    Html_url = models.URLField(null=True)
    # 项目名称
    project_name = models.CharField(max_length=50, null=True)

    class Meta:
        verbose_name_plural = '项目'

    def __str__(self):
        return self.full_name


class Commit(models.Model):

    author_name = models.CharField(max_length=100, null=True)
    author_email = models.EmailField(null=True)
    author_date = models.DateTimeField(default=django.utils.timezone.now, null=True)

    commiter_name = models.CharField(max_length=100, null=True)
    commiter_email = models.EmailField(null=True)
    commiter_date = models.DateTimeField(default=django.utils.timezone.now, null=True)

    sha = models.CharField(max_length=200, primary_key=True)
    message = models.CharField(max_length=100, null=True)
    comment_count = models.IntegerField(null=True)
    project = models.ForeignKey('Project', on_delete=models.CASCADE, null=True)

apps/board/views.py
from django.shortcuts import render
from .models import Project, Commit
from ..mirror_user.models import User, UserContact, UserProfile
import requests
from github import Github
import json
import random
from django.core.mail import send_mail

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36(KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36'
}


def board_settings(request, username):

    user = User.objects.get(username=username)

    try:
        userProfile = user.profile
    except:
        userProfile = UserProfile(user=user)
        userProfile.save()

    if request.method == 'GET':
        return render(request, 'board/settings.html', {'user': user, 'username': username, 'newEmail': ''})
    else:
        if request.POST.get('verification') == '':
            userProfile.verification = random.randint(1000, 9999)
            userProfile.save()
            newEmail = request.POST.get('newEmail')
            send_mail(subject="来自MIRROR公司的邮件", message="【MIRROR】您的验证码是{}，请勿将验证码泄露给他人，如非本人操作请忽略".format(userProfile.verification), from_email="747618283@qq.com", recipient_list=[newEmail,], fail_silently=False)
            return render(request, 'board/settings.html', {'msg_info': "验证码已发送", 'user': user, 'username': username, 'newEmail': newEmail})
        else:
            verification = request.POST.get('verification')
            newEmail = request.POST.get('newEmail')
            if verification == userProfile.verification:
                user.email = newEmail
                user.save()
                return render(request, 'board/settings.html', {'msg_info': "重置邮箱成功", 'user': user, 'username': username, 'newEmail': ''})
            else:
                return render(request, 'board/settings.html', {'msg_info': "验证码错误，请重新核实", 'user': user, 'username': username, 'newEmail': newEmail})


def board_contact(request, username):
    if request.method == 'GET':
        return render(request, 'board/contact.html', {'username': username})
    else:
        user = User.objects.get(username=username)
        theme = request.POST.get('theme')
        info = request.POST.get('info')
        realname = request.POST.get('realname')
        email = request.POST.get('email')
        userContact = UserContact(realname=realname, email=email, info=info, theme=theme, user=user)
        userContact.save()
        return render(request, 'board/contact.html', {'msg_info': "成功提交", 'username': username})


def board_docs(request, username):
    return render(request, 'board/docs.html', {'username': username})


def board_addproject(request, username):
    # 用户增加项目
    if request.method == 'GET':
        return render(request, 'board/addproject.html', {'username': username})
    else:
        full_name = request.POST.get('project_name')
        Description = request.POST.get('project_description')
        project_name = request.POST.get('project_nickname')

        try:
            pro = Project.objects.get(full_name=full_name)
            users = pro.users_participated.filter(username=username)
            if len(users) > 0:
                return render(request, 'board/addproject.html', {'msg_info': "项目已加入", 'username': username})
            else:
                user = User.objects.get(username=username)
                pro.users_participated.add(user)
                return render(request, 'board/addproject.html', {'msg_info': "加入项目成功", 'username': username})
        except:
            project = get_info_from_github(username, full_name, Description, project_name)
            project.save()
            return render(request, 'board/addproject.html', {'msg_info': "项目创建成功", 'username': username})


def board_projects(request, username):
    user = User.objects.get(username=username)
    # 获取项目信息
    projects = user.usersParticipated.all()
    return render(request, 'board/projects.html', {'projects': projects, 'username': username})


def board_delete(request, username, project_name):
    project = Project.objects.get(project_name=project_name)
    user = User.objects.get(username=username)
    project.users_participated.remove(user)
    projects = user.usersParticipated.all()
    return render(request, 'board/projects.html', {'projects': projects, 'username': username})


def board_mainboard(request, username, project_name):
    project = Project.objects.get(project_name=project_name)
    return render(request, 'board/mainboard.html', {'project': project, 'username': username})

def board_calendar(request, username):
    return render(request, 'board/calendar.html', {'username': username})


def board_chart1(request, username, project_name):
    project = Project.objects.get(project_name=project_name)
    return render(request, 'board/chart1.html', {'project': project, 'username': username})

def board_chart2(request, username, project_name):
    project = Project.objects.get(project_name=project_name)
    return render(request, 'board/chart2.html', {'project': project, 'username': username})

def board_chart3(request, username, project_name):
    project = Project.objects.get(project_name=project_name)
    return render(request, 'board/chart3.html', {'project': project, 'username': username})

def board_table1(request, username, project_name):
    project = Project.objects.get(project_name=project_name)
    return render(request, 'board/table1.html', {'project': project, 'username': username})

def board_table2(request, username, project_name):
    project = Project.objects.get(project_name=project_name)
    return render(request, 'board/table2.html', {'project': project, 'username': username})


def get_info_from_github(username, full_name, Description, project_name):

    user = User.objects.get(username=username)
    # pygithub object
    g = Github()

    repo = g.get_repo(full_name)

    project_id = repo.id

    full_name = repo.full_name

    Description = repo.description

    Date_created = repo.created_at

    Date_of_lastpush = repo.pushed_at

    Language = repo.language
    
    Home_page = repo.homepage

    Number_of_forks = repo.forks
    # number of stars
    Number_of_stars = repo.stargazers_count

    Html_url = repo.html_url

    url = repo.commits_url.replace('{/sha}', '')

    rep = requests.get(url=url, headers=headers)

    results = json.loads(rep.text)

    project = Project(project_id=project_id, full_name=full_name, Description=Description, Date_created=Date_created, Date_of_lastpush=Date_of_lastpush, Language=Language, 
                      Home_page=Home_page, Number_of_forks=Number_of_forks, Number_of_stars=Number_of_stars, Html_url=Html_url, project_name=project_name)

    project.save()

    project.users_participated.add(user)

    project.save()

    for result in results:
        sha = result.get('sha')
        author_name = result.get('author').get('name')
        author_email = result.get('author').get('email')
        author_date = result.get('author').get('date')
        message = result.get('message')
        comment_count = result.get('comment_count')
        if result.get('commiter') is None:
            commit = Commit(sha=sha, author_name=author_name, author_email=author_email, author_date=author_date, message=message, comment_count=comment_count, project=project)

        else:
            commiter_name = result.get('commiter').get('name')
            commiter_email = result.get('commiter').get('email')
            commiter_date = result.get('commiter').get('date')
            commit = Commit(sha=sha, author_name=author_name, author_email=author_email, author_date=author_date, commiter_name=commiter_name,
                            commiter_email=commiter_email, commiter_date=commiter_date, message=message, comment_count=comment_count, project=project)

        commit.save()

    return project

front/templates/board/addproject.html
{% extends 'board/base/board_base.html' %}

{% block title %}
增加项目

{% endblock %}


{% block head %}


{% endblock %}



{% block main %}
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>增加项目</h1>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <!-- left column -->
        <div class="col-md-6">
          <!-- general form elements -->
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title"></h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <h3>{{msg_info}}</h3>
            
            <!-- url 'board:addproject'/{{request.session.User.uid}} -->
 
            <form action="{% url 'board:addproject' 'whisper' %}" method="post">
              {% csrf_token %}
              <div class="card-body">
                <div class="form-group">
                  <label for="project_name">Github中的项目名称</label>
                  <input type="text" class="form-control" id="project_name" placeholder="请输入项目名称" name="project_name">
                </div>
                <div class="form-group">
                  <label for="project_description">项目描述</label>
                  <input type="text" class="form-control" id="project_description" placeholder="请输入项目描述" name="project_description">
                </div>
                <div class="form-group">
                    <label for="project_url">项目名称</label>
                    <input type="text" class="form-control" id="project_url" placeholder="请输入项目链接" name="project_nickname">
                </div>
              </div>
              <!-- /.card-body -->

              <div class="card-footer">
                <button type="submit" class="btn btn-primary" style="float:right">添加</button>
              </div>
            </form>
          </div>
          <!-- /.card -->


        </div>
        <!--/.col (left) -->
        <!-- right column -->
        <div class="col-md-6">

        </div>
        <!--/.col (right) -->
      </div>
      <!-- /.row -->
    </div><!-- /.container-fluid -->
  </section>
  <!-- /.content -->

{% endblock %}

front/templates/board/calendar.html
{% extends 'board/base/board_base.html' %}

{% block title %}
日历

{% endblock %}


{% block head %}


{% endblock %}



{% block main %}
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">日历</h1>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">

        <!-- Main row -->
        <div class="row">
          <!-- Left col -->
          <section class="col-lg-5 connectedSortable">
            <!-- Calendar -->
            <div class="card bg-gradient-success">

                <div class="card-header border-0">
  
                  <h3 class="card-title">
                    <i class="far fa-calendar-alt"></i>
                     
                  </h3>
                  <!-- tools card -->
                  <div class="card-tools">
                    <!-- button with a dropdown -->

                    <button type="button" class="btn btn-success btn-sm" data-card-widget="collapse">
                      <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-success btn-sm" data-card-widget="remove">
                      <i class="fas fa-times"></i>
                    </button>
                  </div>
                  <!-- /. tools -->
                </div>
                <!-- /.card-header -->
                <div class="card-body pt-0">
                  <!--The calendar -->
                  <div id="calendar" style="width: 100%"></div>
                </div>
                <!-- /.card-body -->
              </div>
              <!-- /.card -->


            <!-- Map card -->
            <div class="card bg-gradient-primary " style="display:none">
                <div class="card-header border-0">
                  <h3 class="card-title">
                    <i class="fas fa-map-marker-alt mr-1"></i>
                    地图
                  </h3>
                </div>
                <!-- /.card-body-->
                <div class="card-footer">
                  <div class="row">
                    <div class="col-4 text-center">
                      <div id="sparkline-1"></div>
                    </div>
                    <!-- ./col -->
                    <div class="col-4 text-center">
                      <div id="sparkline-2"></div>
                    </div>
                    <!-- ./col -->
                    <div class="col-4 text-center">
                      <div id="sparkline-3"></div>
                    </div>
                    <!-- ./col -->
                  </div>
                  <!-- /.row -->
                </div>
            </div>
            <!-- /.card -->
          </section>
          <!-- /.Left col -->
          <!-- right col (We are only adding the ID to make the widgets sortable)-->
          <section class="col-lg-5 connectedSortable">
  



            
          </section>
          <!-- right col -->
        </div>
        <!-- /.row (main row) -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->

{% endblock %}

front/templates/board/contact.html
{% extends 'board/base/board_base.html' %}

{% block title %}
联系我们

{% endblock %}


{% block head %}


{% endblock %}



{% block main %}
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>联系我们</h1>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">

    <!-- Default box -->
    <div class="card">
      <div class="card-body row">
        <div class="col-5 text-center d-flex align-items-center justify-content-center">
          <div class="">
            <h2><img src={% static 'adminlte/dist/img/logo.png'%} alt="mirror-logo" height=70px></h2>
            <br>
            <p class="lead mb-5">地址：浙江大学玉泉校区<br>
              邮箱: <a href="mailto:contact@zjues.com">contact@zjues.com</a>
            </p>
          </div>
        </div>
        <form action="{% url 'board:contact' username %}" method="post" class="col-7">
          {% csrf_token %}
          <label for="inputMessage">{{msg_info}}</label>
          <div class="form-group">
            <label for="inputName">您的姓名</label>
            <input type="text" id="inputName" class="form-control", name="realname"/>
          </div>
          <div class="form-group">
            <label for="inputEmail">您的邮箱</label>
            <input type="email" id="inputEmail" class="form-control", name="email" />
          </div>
          <div class="form-group">
            <label for="inputSubject">反馈主题</label>
            <input type="text" id="inputSubject" class="form-control", name="theme" />
          </div>
          <div class="form-group">
            <label for="inputMessage">详细信息</label>
            <textarea id="inputMessage" class="form-control" rows="4", name="info" ></textarea>
          </div>
          <div class="form-group">
            <input type="submit" class="btn btn-primary" value="提交">
          </div>
        </form>
      </div>
    </div>

  </section>
  <!-- /.content -->

{% endblock %}

front/templates/board/docs.html
{% extends 'board/base/board_base.html' %}

{% block title %}
使用说明

{% endblock %}


{% block head %}


{% endblock %}



{% block main %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1>FAQ</h1>
            </div>
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active">FAQ</li>
              </ol>
            </div>
          </div>
        </div><!-- /.container-fluid -->
      </section>
  
      <!-- Main content -->
      <section class="content">
          <div class="row">
              <div class="col-12" id="accordion">
                  <div class="card card-primary card-outline">
                      <a class="d-block w-100" data-toggle="collapse" href="#collapseOne">
                          <div class="card-header">
                              <h4 class="card-title w-100">
                                  1. Mirror是用来干什么的？
                              </h4>
                          </div>
                      </a>
                      <div id="collapseOne" class="collapse show" data-parent="#accordion">
                          <div class="card-body">
                              Mirror是一款开源软件开发分析工具，可以跟踪和分析软件开发的流程。
                          </div>
                      </div>
                  </div>
                  <div class="card card-primary card-outline">
                      <a class="d-block w-100" data-toggle="collapse" href="#collapseTwo">
                          <div class="card-header">
                              <h4 class="card-title w-100">
                                  2. Mirror支持哪些平台的项目跟踪？
                              </h4>
                          </div>
                      </a>
                      <div id="collapseTwo" class="collapse" data-parent="#accordion">
                          <div class="card-body">
                              目前，Mirror暂时只支持Github平台的项目，其它平台的项目我们也会陆续接入。
                          </div>
                      </div>
                  </div>
                  <div class="card card-primary card-outline">
                      <a class="d-block w-100" data-toggle="collapse" href="#collapseThree">
                          <div class="card-header">
                              <h4 class="card-title w-100">
                                  3. 这里填一个关于Mirror的问题。
                              </h4>
                          </div>
                      </a>
                      <div id="collapseThree" class="collapse" data-parent="#accordion">
                          <div class="card-body">
                              这里放上对应的回答。
                          </div>
                      </div>
                  </div>
              </div>
          </div>

      </section>
      <!-- /.content -->

{% endblock %}

front/templates/board/mainboard.html
{% extends 'board/base/project_base.html' %}

{% block title %}
项目面板

{% endblock %}


{% block head %}


{% endblock %}



{% block main %}
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>项目面板</h1>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <!-- left column -->
        <div class="col-md-6">
          <!-- general form elements -->
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">项目信息</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <div>
              <div class="card-body">
                <div class="form-group">
                  <label for="exampleInputEmail1">项目名称</label>
                  <input type="email" class="form-control" id="exampleInputEmail1" placeholder={{project.project_name}} disabled>
                </div>
              </div>
              <div class="card-body">
                <div class="form-group">
                  <label for="exampleInputEmail1">创建时间</label>
                  <input type="email" class="form-control" id="exampleInputEmail1" placeholder={{project.Date_created}} disabled>
                </div>
              </div>
              <div class="card-body">
                <div class="form-group">
                  <label for="exampleInputEmail1">上次提交时间</label>
                  <input type="email" class="form-control" id="exampleInputEmail1" placeholder={{project.Date_of_lastpush}} disabled>
                </div>
              </div>
              <div class="card-body">
                <div class="form-group">
                  <label for="exampleInputEmail1">使用语言</label>
                  <input type="email" class="form-control" id="exampleInputEmail1" placeholder={{project.Language}} disabled>
                </div>
              </div>              
              <div class="card-body">
                <div class="form-group">
                  <label for="exampleInputEmail1">fork数目</label>
                  <input type="email" class="form-control" id="exampleInputEmail1" placeholder={{project.Number_of_forks}} disabled>
                </div>
              </div>              
              <div class="card-body">
                <div class="form-group">
                  <label for="exampleInputEmail1">星级</label>
                  <input type="email" class="form-control" id="exampleInputEmail1" placeholder={{project.Number_of_stars}} disabled>
                </div>
              </div>
              <div class="card-body">
                <div class="form-group">
                  <label for="exampleInputEmail1">地址</label>
                  <input type="email" class="form-control" id="exampleInputEmail1" placeholder={{project.Html_url}} disabled>
                </div>
              </div>
              
              <!-- /.card-body -->
            </div>
          </div>
          <!-- /.card -->

          <!-- Horizontal Form -->

          <!-- /.card -->

        </div>
        <!--/.col (left) -->
        <!-- right column -->
        <div class="col-md-6">

      </div>
      <!-- /.row -->
    </div><!-- /.container-fluid -->
  </section>
  <!-- /.content -->

{% endblock %}

front/templates/board/projects.html
{% extends 'board/base/board_base.html' %}

{% block title %}
我的项目

{% endblock %}


{% block head %}


{% endblock %}



{% block main %}
 <!-- Content Header (Page header) -->
 <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>我的项目</h1>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>

  <!-- Main content -->
  <section class="content">

    <!-- Default box -->
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">项目列表</h3>

        <div class="card-tools">
          <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
            <i class="fas fa-minus"></i>
          </button>
          <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
            <i class="fas fa-times"></i>
          </button>
        </div>
      </div>
      <div class="card-body p-0">
        <table class="table table-striped projects">
            <thead>
                <tr>
                    <th style="width: 5%">
                        ID
                    </th>
                    <th style="width: 20%">
                        项目名
                    </th>
                    <th style="width: 30%">
                        项目描述
                    </th>
                    <th>
                        创建时间
                    </th>
                    <th style="width: 8%" class="text-center">
                        跟踪状态
                    </th>
                    <th style="width: 20%">
                    </th>
                </tr>
            </thead>
            <tbody>
                <script>
                  var ID = 1;
                </script>
                {% for project in projects %}
                <tr>
                    <td>
                      <script>
                        document.write(ID++);
                      </script>
                    </td>
                    <td>
                        <a>
                            {{project.project_name}}
                        </a>
                    </td>
                    <td>
                        {{project.Description}}
                    </td>
                    <td class="project_progress">
                        {{project.Date_created}}
                    </td>
                    <td class="project-state">
                        <span class="badge badge-success">正常</span>
                    </td>
                    <td class="project-actions text-right">
                        <a class="btn btn-primary btn-sm" href="{%  url 'board:mainboard' username project.project_name %}">
                            <i class="fas fa-folder">
                            </i>
                            查看
                        </a>
                        <a class="btn btn-danger btn-sm" href="{%  url 'board:delete' username project.project_name %}">
                            <i class="fas fa-trash">
                            </i>
                            删除
                        </a>
                    </td>
                </tr>
                {% endfor%}
              
            </tbody>
        </table>
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.card -->

  </section>
  <!-- /.content -->

{% endblock %}