MIRROR/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.contrib.staticfiles.views import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='mirror_user/login/')),
    path('mirror_user/', include('apps.mirror_user.urls')),
    path('board/', include('apps.board.urls')),
    path('favicon.ico', serve, {'path': 'adminlte/dist/img/favicon.ico'}),

]

apps/board/urls.py
from django.urls import path,include
from django.views.generic import RedirectView
from . import views

app_name = "board"

urlpatterns = [
    path("<str:username>/", include([
        path('', RedirectView.as_view(url='projects/')),
        path("addproject/", views.board_addproject, name="addproject"),
        path("contact/", views.board_contact, name="contact"),
        path("docs/", views.board_docs, name="docs"),
        path("mainboard/<str:project_name>/", views.board_mainboard, name="mainboard"),
        path("projects/", views.board_projects, name="projects"),
        path("chart1/<str:project_name>/", views.board_chart1, name="chart1"),
        path("chart2/<str:project_name>/", views.board_chart2, name="chart2"),
        path("chart3/<str:project_name>/", views.board_chart3, name="chart3"),
        path("delete/<str:project_name>/", views.board_delete, name="delete"),
        path("table1/<str:project_name>/", views.board_table1, name="table1"),
        path("table2/<str:project_name>/", views.board_table2, name="table2"),
        path("settings/", views.board_settings, name="settings"),
        path("calendar/", views.board_calendar, name="calendar"),
    ]))
]

apps/board/models.py
from django.db import models
import django
from django.contrib.auth.models import User


# # Create your models here.
class Project(models.Model):

    users_participated = models.ManyToManyField(to=User, related_name='usersParticipated')

    project_id = models.CharField(max_length=50, null=True)
    # repository full name
    full_name = models.CharField(max_length=50, null=True)
    # repository description
    Description = models.CharField(max_length=100, null=True)
    # the date of when the repo was created
    Date_created = models.DateTimeField(default=django.utils.timezone.now, null=True)
    # the date of the last git push
    Date_of_lastpush = models.DateTimeField(default=django.utils.timezone.now, null=True)
    # programming language
    Language = models.CharField(max_length=50, null=True)
    # number of forks
    Number_of_forks = models.IntegerField(null=True)
    # number of stars
    Number_of_stars = models.IntegerField(null=True)
    # home page
    Home_page = models.CharField(max_length=50, null=True)
    # html url
    Html_url = models.URLField(null=True)
    # 项目名称
    project_name = models.CharField(max_length=50, null=True)

    class Meta:
        verbose_name_plural = '项目'

    def __str__(self):
        return self.full_name


class Commit(models.Model):

    author_name = models.CharField(max_length=100, null=True)
    author_email = models.EmailField(null=True)
    author_date = models.DateTimeField(default=django.utils.timezone.now, null=True)

    commiter_name = models.CharField(max_length=100, null=True)
    commiter_email = models.EmailField(null=True)
    commiter_date = models.DateTimeField(default=django.utils.timezone.now, null=True)

    sha = models.CharField(max_length=200, primary_key=True)
    message = models.CharField(max_length=100, null=True)
    comment_count = models.IntegerField(null=True)
    project = models.ForeignKey('Project', on_delete=models.CASCADE, null=True)

apps/board/views.py
from django.shortcuts import render
from .models import Project, Commit
from ..mirror_user.models import User, UserContact, UserProfile
import requests
from github import Github
import json
import random
from django.core.mail import send_mail

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36(KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36'
}


def board_settings(request, username):

    user = User.objects.get(username=username)

    try:
        userProfile = user.profile
    except:
        userProfile = UserProfile(user=user)
        userProfile.save()

    if request.method == 'GET':
        return render(request, 'board/settings.html', {'user': user, 'username': username, 'newEmail': ''})
    else:
        if request.POST.get('verification') == '':
            userProfile.verification = random.randint(1000, 9999)
            userProfile.save()
            newEmail = request.POST.get('newEmail')
            send_mail(subject="来自MIRROR公司的邮件", message="【MIRROR】您的验证码是{}，请勿将验证码泄露给他人，如非本人操作请忽略".format(userProfile.verification), from_email="747618283@qq.com", recipient_list=[newEmail,], fail_silently=False)
            return render(request, 'board/settings.html', {'msg_info': "验证码已发送", 'user': user, 'username': username, 'newEmail': newEmail})
        else:
            verification = request.POST.get('verification')
            newEmail = request.POST.get('newEmail')
            if verification == userProfile.verification:
                user.email = newEmail
                user.save()
                return render(request, 'board/settings.html', {'msg_info': "重置邮箱成功", 'user': user, 'username': username, 'newEmail': ''})
            else:
                return render(request, 'board/settings.html', {'msg_info': "验证码错误，请重新核实", 'user': user, 'username': username, 'newEmail': newEmail})


def board_contact(request, username):
    if request.method == 'GET':
        return render(request, 'board/contact.html', {'username': username})
    else:
        user = User.objects.get(username=username)
        theme = request.POST.get('theme')
        info = request.POST.get('info')
        realname = request.POST.get('realname')
        email = request.POST.get('email')
        userContact = UserContact(realname=realname, email=email, info=info, theme=theme, user=user)
        userContact.save()
        return render(request, 'board/contact.html', {'msg_info': "成功提交", 'username': username})


def board_docs(request, username):
    return render(request, 'board/docs.html', {'username': username})


def board_addproject(request, username):
    # 用户增加项目
    if request.method == 'GET':
        return render(request, 'board/addproject.html', {'username': username})
    else:
        full_name = request.POST.get('project_name')
        Description = request.POST.get('project_description')
        project_name = request.POST.get('project_nickname')

        try:
            pro = Project.objects.get(full_name=full_name)
            users = pro.users_participated.filter(username=username)
            if len(users) > 0:
                return render(request, 'board/addproject.html', {'msg_info': "项目已加入", 'username': username})
            else:
                user = User.objects.get(username=username)
                pro.users_participated.add(user)
                return render(request, 'board/addproject.html', {'msg_info': "加入项目成功", 'username': username})
        except:
            project = get_info_from_github(username, full_name, Description, project_name)
            project.save()
            return render(request, 'board/addproject.html', {'msg_info': "项目创建成功", 'username': username})


def board_projects(request, username):
    user = User.objects.get(username=username)
    # 获取项目信息
    projects = user.usersParticipated.all()
    return render(request, 'board/projects.html', {'projects': projects, 'username': username})


def board_delete(request, username, project_name):
    project = Project.objects.get(project_name=project_name)
    user = User.objects.get(username=username)
    project.users_participated.remove(user)
    projects = user.usersParticipated.all()
    return render(request, 'board/projects.html', {'projects': projects, 'username': username})


def board_mainboard(request, username, project_name):
    project = Project.objects.get(project_name=project_name)
    return render(request, 'board/mainboard.html', {'project': project, 'username': username})

def board_calendar(request, username):
    return render(request, 'board/calendar.html', {'username': username})


def board_chart1(request, username, project_name):
    project = Project.objects.get(project_name=project_name)
    return render(request, 'board/chart1.html', {'project': project, 'username': username})

def board_chart2(request, username, project_name):
    project = Project.objects.get(project_name=project_name)
    return render(request, 'board/chart2.html', {'project': project, 'username': username})

def board_chart3(request, username, project_name):
    project = Project.objects.get(project_name=project_name)
    return render(request, 'board/chart3.html', {'project': project, 'username': username})

def board_table1(request, username, project_name):
    project = Project.objects.get(project_name=project_name)
    return render(request, 'board/table1.html', {'project': project, 'username': username})

def board_table2(request, username, project_name):
    project = Project.objects.get(project_name=project_name)
    return render(request, 'board/table2.html', {'project': project, 'username': username})


def get_info_from_github(username, full_name, Description, project_name):

    user = User.objects.get(username=username)
    # pygithub object
    g = Github()

    repo = g.get_repo(full_name)

    project_id = repo.id

    full_name = repo.full_name

    Description = repo.description

    Date_created = repo.created_at

    Date_of_lastpush = repo.pushed_at

    Language = repo.language
    
    Home_page = repo.homepage

    Number_of_forks = repo.forks
    # number of stars
    Number_of_stars = repo.stargazers_count

    Html_url = repo.html_url

    url = repo.commits_url.replace('{/sha}', '')

    rep = requests.get(url=url, headers=headers)

    results = json.loads(rep.text)

    project = Project(project_id=project_id, full_name=full_name, Description=Description, Date_created=Date_created, Date_of_lastpush=Date_of_lastpush, Language=Language, 
                      Home_page=Home_page, Number_of_forks=Number_of_forks, Number_of_stars=Number_of_stars, Html_url=Html_url, project_name=project_name)

    project.save()

    project.users_participated.add(user)

    project.save()

    for result in results:
        sha = result.get('sha')
        author_name = result.get('author').get('name')
        author_email = result.get('author').get('email')
        author_date = result.get('author').get('date')
        message = result.get('message')
        comment_count = result.get('comment_count')
        if result.get('commiter') is None:
            commit = Commit(sha=sha, author_name=author_name, author_email=author_email, author_date=author_date, message=message, comment_count=comment_count, project=project)

        else:
            commiter_name = result.get('commiter').get('name')
            commiter_email = result.get('commiter').get('email')
            commiter_date = result.get('commiter').get('date')
            commit = Commit(sha=sha, author_name=author_name, author_email=author_email, author_date=author_date, commiter_name=commiter_name,
                            commiter_email=commiter_email, commiter_date=commiter_date, message=message, comment_count=comment_count, project=project)

        commit.save()

    return project

front/templates/board/base/board_base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="keywords" content="Mirror,开源,项目,可视化,分析工具">
  <meta name="description" content="Mirror-开源项目可视化分析工具">
  <title>{% block title %} {% endblock %}-Mirror项目可视化分析工具</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'adminlte/plugins/fontawesome-free/css/all.min.css'%}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'adminlte/dist/css/ionicons.min.css'%}">
  <!-- Tempusdominus Bootstrap 4 -->
  <link rel="stylesheet" href="https://cdn.bootcdn.net/ajax/libs/tempusdominus-bootstrap-4/5.39.0/css/tempusdominus-bootstrap-4.min.css">
  <!-- iCheck -->
  <link rel="stylesheet" href="https://cdn.bootcdn.net/ajax/libs/icheck-bootstrap/3.0.1/icheck-bootstrap.min.css">
  <!-- JQVMap -->
  <link rel="stylesheet" href="https://cdn.bootcdn.net/ajax/libs/jqvmap/1.5.1/jqvmap.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="https://cdn.bootcdn.net/ajax/libs/admin-lte/3.1.0/css/adminlte.min.css">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="https://cdn.bootcdn.net/ajax/libs/overlayscrollbars/1.13.0/css/OverlayScrollbars.min.css">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="https://cdn.bootcdn.net/ajax/libs/bootstrap-daterangepicker/3.1/daterangepicker.min.css">
  <!-- summernote -->
  <link rel="stylesheet" href="https://cdn.bootcdn.net/ajax/libs/summernote/0.8.18/summernote-bs4.min.css">
  <!-- jQuery -->
  <script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <!-- jQuery UI 1.11.4 -->
  <script src="https://cdn.bootcdn.net/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
  <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
  <script>
    $.widget.bridge('uibutton', $.ui.button)
  </script>
  <!-- Bootstrap 4 -->
  <script src="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.bundle.min.js"></script>
  <!-- ChartJS -->
  <script src="https://cdn.bootcdn.net/ajax/libs/Chart.js/2.9.4/Chart.min.js"></script>
  <!-- Sparkline -->
  <script src="{% static 'adminlte/plugins/sparklines/sparkline.js'%}"></script>
  <!-- JQVMap -->
  <script src="https://cdn.bootcdn.net/ajax/libs/jqvmap/1.5.1/jquery.vmap.min.js"></script>
  <script src="https://cdn.bootcdn.net/ajax/libs/jqvmap/1.5.1/maps/jquery.vmap.usa.js"></script>
  <!-- jQuery Knob Chart -->
  <script src="{% static 'adminlte/plugins/jquery-knob/jquery.knob.min.js'%}"></script>
  <!-- daterangepicker -->
  <script src="{% static 'adminlte/plugins/moment/moment.min.js'%}"></script>
  <script src="https://cdn.bootcdn.net/ajax/libs/bootstrap-daterangepicker/3.1/daterangepicker.min.js"></script>
  <!-- Tempusdominus Bootstrap 4 -->
  <script src="https://cdn.bootcdn.net/ajax/libs/tempusdominus-bootstrap-4/5.39.0/js/tempusdominus-bootstrap-4.min.js"></script>
  <!-- Summernote -->
  <script src="{% static 'adminlte/plugins/summernote/summernote-bs4.min.js'%}"></script>
  <!-- overlayScrollbars -->
  <script src="https://cdn.bootcdn.net/ajax/libs/overlayscrollbars/1.13.0/js/OverlayScrollbars.min.js"></script>
  <!-- AdminLTE App -->
  <script src="https://cdn.bootcdn.net/ajax/libs/admin-lte/3.1.0/js/adminlte.min.js"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="{% static 'adminlte/dist/js/demo.js'%}"></script>
  <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
  <script src="{% static 'adminlte/dist/js/pages/dashboard.js'%}"></script>
  {% block head %} {% endblock %}
</head>


<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">
  <!-- Preloader -->
  <div class="preloader flex-column justify-content-center align-items-center" >
    <img class="" src="{% static 'adminlte/dist/img/logo.png'%}" alt="mirrorlogo" height="116" width="293" >
  </div>

  <!-- Navbar -->
  {% include 'board/base/navbar_base.html' %}
  

  <!-- Main Sidebar Container -->
  {% include 'board/base/sidebar_base.html' %}



  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    {% block main %}

    {% endblock %}
  </div>


  <!-- /.content-wrapper -->

  <!-- footer -->
  {% include 'board/base/footer_base.html' %}

</div>
<!-- ./wrapper -->
</body>
</html>

front/templates/board/base/contentheader_base.html
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0">Dashboard</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="#">Home</a></li>
          <li class="breadcrumb-item active">面板1</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

front/templates/board/base/footer_base.html
<!-- footer -->
<footer class="main-footer">
  <strong>Copyright &copy; 2021 <a href="#">Mirror</a>.</strong>
  All rights reserved.
  <div class="float-right d-none d-sm-inline-block">
    <b>Version</b> 1.1.0
  </div>
</footer>

front/templates/board/base/navbar_base.html
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="index3.html" class="nav-link"> </a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      <!--
      <li class="nav-item">
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
          <i class="fas fa-search"></i>
        </a>
        <div class="navbar-search-block">
          <form class="form-inline">
            <div class="input-group input-group-sm">
              <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                  <i class="fas fa-search"></i>
                </button>
                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>-->

      <!-- Fullscreen -->
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
       <!-- 无用部分
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        -->
        </a>
      </li>
    </ul>
  </nav>

front/templates/board/base/project_sidebar.html
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
      <img src="{% static 'adminlte/dist/img/logo3.png'%}" alt="mirrorlogo" class="brand-image img-circle elevation-3" style="opacity: 100 ! important;">
      <span class="brand-text font-weight-light">项目分析工具</span>
    </a>
  
    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex" margin:"auto 0">
        <div class="image">
          <img src="{% static 'adminlte/dist/img/userAvatar1.png'%}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">UserAdmin</a>
        </div>
      </div>
  
  
      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item">
            <a href="{% url 'board:projects' username %}" class="nav-link">
                <i class="nav-icon fas fa-th"></i>
                <p>我的项目</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'board:mainboard' username project.project_name %}" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                面板
              </p>
            </a>
          </li>

          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-chart-pie"></i>
              <p>
                图表
                <i class="right fas fa-angle-right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'board:chart1' username project.project_name %}" class="nav-link">
                  <i class="nav-icon far fa-circle text-warning"></i>
                  <p>图表1</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'board:chart2' username project.project_name %}" class="nav-link">
                  <i class="nav-icon far fa-circle text-info"></i>
                  <p>图表2</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'board:chart3' username project.project_name %}" class="nav-link">
                  <i class="nav-icon far fa-circle text-danger"></i>
                  <p>图表3</p>
                </a>
              </li>
            </ul>
          </li>

          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-table"></i>
              <p>
                表格
                <i class="fas fa-angle-right right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'board:table1' username project.project_name %}" class="nav-link">
                  <i class="nav-icon far fa-circle text-warning"></i>
                  <p>表格1</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'board:table2' username project.project_name %}" class="nav-link">
                  <i class="nav-icon far fa-circle text-info"></i>
                  <p>表格2</p>
                </a>
              </li>
            </ul>

          </li>
      
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

front/templates/board/base/sidebar_base.html
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <a href="#" class="brand-link">
    <img src="{% static 'adminlte/dist/img/logo3.png'%}" alt="mirrorlogo" class="brand-image img-circle elevation-3" style="opacity: 100 ! important;">
    <span class="brand-text font-weight-light">项目分析工具</span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex" margin:"auto 0">
      <div class="image">
        <img src="{% static 'adminlte/dist/img/userAvatar1.png'%}" class="img-circle elevation-2" alt="User Image">
      </div>
      <div class="info">
        <a href="#" class="d-block">UserAdmin</a>
      </div>
    </div>


    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
             with font-awesome or any other icon font library -->
        <li class="nav-item">
          <a href="{% url 'board:projects' username %}" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>我的项目</p>
          </a>
        </li>
        <!-- <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="nav-icon fas fa-chart-pie"></i>
            <p>
              项目
              <i class="right fas fa-angle-right"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'board:mainboard' username "奥运奖牌榜" %}" class="nav-link">
                <i class="nav-icon fas fa-tachometer-alt"></i>
                <p>
                  面板
                </p>
              </a>
            </li>
            <li class="nav-item">
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="nav-icon fas fa-chart-pie"></i>
                  <p>
                    图表
                    <i class="right fas fa-angle-right"></i>
                  </p>
                </a>
                <ul class="nav nav-treeview">
                  <li class="nav-item">
                    <a href="{% url 'board:chart1' username "奥运奖牌榜" %}" class="nav-link">
                      <i class="nav-icon far fa-circle text-warning"></i>
                      <p>图表1</p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="{% url 'board:chart2' username "奥运奖牌榜" %}" class="nav-link">
                      <i class="nav-icon far fa-circle text-info"></i>
                      <p>图表2</p>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a href="{% url 'board:chart3' username "奥运奖牌榜" %}" class="nav-link">
                      <i class="nav-icon far fa-circle text-danger"></i>
                      <p>图表3</p>
                    </a>
                  </li>
                </ul>
              </li>

            </li>
            <li class="nav-item">
              <a href="#" class="nav-link">
                <i class="nav-icon fas fa-table"></i>
                <p>
                  表格
                  <i class="fas fa-angle-right right"></i>
                </p>
              </a>
              <ul class="nav nav-treeview">
                <li class="nav-item">
                  <a href="{% url 'board:table1' username "奥运奖牌榜" %}" class="nav-link">
                    <i class="nav-icon far fa-circle text-warning"></i>
                    <p>表格1</p>
                  </a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'board:table2' username "奥运奖牌榜" %}" class="nav-link">
                    <i class="nav-icon far fa-circle text-info"></i>
                    <p>表格2</p>
                  </a>
                </li>
              </ul>

            </li>
          </ul>
        </li>      -->
        
        <li class="nav-item">
          <a href="{% url 'board:addproject' username %}" class="nav-link">
            <i class="nav-icon far fa-circle fa-plus-square"></i>
            <p>增加项目</p>
          </a>
        </li>

        <li class="nav-item">
          <a href="{% url 'board:settings' username %}" class="nav-link">
            <i class="nav-icon fas fa-edit"></i>
            <p>设置中心</p>
          </a>
        </li>

        <li class="nav-header">工具中心</li>
        <li class="nav-item">
          <a href="{% url 'board:calendar' username %}" class="nav-link">
            <i class="nav-icon far fa-calendar-alt"></i>
            <p>
              日历
            </p>
          </a>
        </li>          

        <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="nav-icon fas fa-book"></i>
            <p>
              帮助
              <i class="fas fa-angle-right right"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'board:docs' username %}" class="nav-link">
                <i class="nav-icon far fa-circle text-warning"></i>
                <p>使用说明</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'board:contact' username %}" class="nav-link">
                <i class="nav-icon far fa-circle text-info"></i>
                <p>联系我们</p>
              </a>
            </li>
          </ul>
        </li>
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>