MIRROR/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.contrib.staticfiles.views import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='mirror_user/login/')),
    path('mirror_user/', include('apps.mirror_user.urls')),
    path('board/', include('apps.board.urls')),
    path('favicon.ico', serve, {'path': 'adminlte/dist/img/favicon.ico'}),

]

apps/mirror_user/urls.py
from django.urls import path
from . import views
app_name = 'mirror_user'
urlpatterns = [
    path('login/', views.user_login, name="user_login"),
    path('register/', views.user_register, name="user_register"),
    path('logout/', views.user_logout, name="user_logout"),
    path("register_terms/", views.user_registerterms, name="user_registerterms"),
    path("forget_password/", views.user_forgetpassword, name="user_forgetpassword"),
    path("recover_password/", views.user_recoverpassword, name="user_recoverpassword"),
]

apps/mirror_user/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfile(models.Model):
    C_GENDER = (
        ('0', '女'),
        ('1', '男')
    )
    # 用户
    user = models.OneToOneField(verbose_name="用户", to=User, related_name="profile", on_delete=models.CASCADE)
    # 性别
    gender = models.CharField(max_length=5, verbose_name="性别", choices=C_GENDER, default='1')
    # 年龄
    age = models.IntegerField(verbose_name="年龄", default=0)
    # 手机
    phone = models.CharField(max_length=15, verbose_name="手机", null=True, blank=True)
    # 组织
    org = models.CharField(verbose_name="组织", max_length=200, null=True, blank=True)
    # 简介
    intro = models.TextField(verbose_name="简介", null=True, blank=True)
    # 邮箱验证码
    verification = models.CharField(max_length=5, verbose_name="验证码", default="0", null=True, blank=True)  


class UserContact(models.Model):
    # 用户
    user = models.ForeignKey(verbose_name="用户", to=User, related_name="contact", on_delete=models.CASCADE)
    # 主题
    theme = models.TextField(verbose_name="主题", null=True, blank=True)
    # 信息
    info = models.TextField(verbose_name="信息", null=True, blank=True)

    realname = models.CharField(max_length=15, verbose_name="真实姓名", null=True, blank=True)

    email = models.EmailField(null=True, blank=True)

apps/mirror_user/forms.py
from django import forms
from django.contrib.auth.models import User


class UserRegisterForm(forms.ModelForm):
    confirm = forms.CharField(label="确认密码", min_length=6, max_length=18)

    class Meta:
        model = User
        fields = ['username', 'password', 'confirm']

    def clean_username(self):
        # 自定义用户名验证规则
        u_list = User.objects.filter(username=self.cleaned_data['username'])
        if len(u_list) > 0:
            raise forms.ValidationError("账号已存在，请使用其他账号注册")
        return self.cleaned_data['username']

    def clean_confirm(self):
        # 自定义确定密码验证规则
        if self.cleaned_data['password'] != self.cleaned_data['confirm']:
            raise forms.ValidationError("两次密码输入不一致")
        return self.cleaned_data['confirm']

apps/mirror_user/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from . import forms
from django.contrib.auth.models import User


# Create your views here.
def user_login(request):
    if request.method == 'GET':
        return render(request, 'mirror_user/login.html', {})
    elif request.method == 'POST':
        # 接受登陆数据
        username = request.POST.get('username')
        password = request.POST.get('password')
        # 验证表单数据
        user = authenticate(request, username=username, password=password)
        if user and user.is_active:
            login(request, user)
            return redirect(reverse("board:projects", args=(user.get_username(),)))
        else:
            return render(request, 'mirror_user/login.html', {'msg_code': "-1", "msg_info": "账号或密码有误"})


def user_logout(request):
    logout(request)
    return redirect(reverse("mirror_user:user_login"))


def user_register(request):
    if request.method == "GET":
        return render(request, "mirror_user/register.html", {})
    elif request.method == "POST":
        # 接受用户注册数据
        form_register = forms.UserRegisterForm(request.POST)
        if form_register.is_valid():
            # 验证通过，创建用户对象
            User.objects.create_user(username=form_register.instance.username, password=form_register.instance.password, email=request.POST.get('email'))
            # 跳转到到登陆页面
            return redirect(reverse("mirror_user:user_login"), kwargs={"msg_code": "0", "msg_info": "注册成功"})
        else:
            return render(request, "mirror_user/register.html", {"form": form_register, "msg_code": "-1", "msg_info": "注册失败"})


def user_registerterms(request):
    return render(request, 'mirror_user/register_terms.html')


def user_forgetpassword(request):
    return render(request, 'mirror_user/forget_password.html')


def user_recoverpassword(request):
    if request.method == "GET":
        return render(request, 'mirror_user/recover_password.html')
    elif request.method == "POST":
        # 接受用户注册数据
        try:
            user = User.objects.get(username=request.POST.get('username'))
            if request.POST.get('password') == request.POST.get('confirm'):
                user.password = request.POST.get('password')
                # 跳转到到登陆页面
                return redirect(reverse("mirror_user:user_login"), kwargs={"msg_code": "0", "msg_info": "密码修改成功"})
            else:
                return render(request, "mirror_user/recover_password.html", {"msg_code": "-1", "msg_info": "两次输入的密码不一致"})
        except:
            return render(request, "mirror_user/recover_password.html", {"msg_code": "-1", "msg_info": "用户不存在"})

front/templates/mirror_user/forget_password.html
{% extends 'mirror_user/base/mirror_user_base.html' %}

{% block title %}忘记密码{% endblock %}

{% block head %}   {% endblock %}

{% block main %}
<body class="hold-transition login-page">
<div class="login-box">
  <div class="card card-outline card-primary">
    <div class="card-header text-center">
      <!--<a href="../../index2.html" class="h1"><b>Mi</b>rror</a>-->
      <img src="{% static 'adminlte/dist/img/logo.png' %}" alt="mirror-logo" height=50px>
    </div>
    <div class="card-body">
      <p class="login-box-msg">请输入你的邮箱地址以重置密码</p>
      <form action="../recover_password/" method="post">
        {% csrf_token %}
        <div class="input-group mb-3">
          <input type="email" class="form-control" placeholder="邮箱">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <button type="submit" class="btn btn-primary btn-block">重置密码</button>
          </div>
          <!-- /.col -->
        </div>
      </form>
      <p class="mt-3 mb-1">
        <a href="../../mirror_user/login/">前往登录</a>
      </p>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->
</body>
{% endblock %}

front/templates/mirror_user/login.html
{% extends 'mirror_user/base/mirror_user_base.html' %}

{% block title %}登录{% endblock %}

{% block head %}   {% endblock %}

{% block main %}
<body class="hold-transition login-page">
<div class="login-box">
  <!-- /.login-logo -->
  <div class="card card-outline card-primary">
    <div class="card-header text-center">
      <!--<a href="../../index2.html" class="h1"><b>Mi</b>rror</a>-->
      <img src="{% static 'adminlte/dist/img/logo.png'%}" alt="mirror-logo" height=50px>
    </div>
    <div class="card-body">
      <p class="login-box-msg"><font color="#007bff">登录以开启全新世界</font></p>
      <p class="login-box-msg">
        {{form.errors}}
        {{msg_info}}
      </p>
      <form action="{% url 'mirror_user:user_login' %}" method="post">
            {% csrf_token %}
        <div class="input-group mb-3">
          <input type="text" class="form-control" placeholder="请输入用户名" name="username" id="username">
          <span style="color: red;">{{form.errors.username}}</span>
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" class="form-control" placeholder="请输入密码" name="password" id="password">
          <span style="color: red;">{{form.errors.password}}</span>
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="remember" value=1>
              <label for="remember">
                记住登录状态
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">登录</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

      
      <!-- /.social-auth-links -->

      <p class="mb-1">
        <a href="../../mirror_user/forget_password">忘记密码？</a>
      </p>
      <p class="mb-0">
        <a href="../../mirror_user/register" class="text-center">注册</a>
      </p>
    </div>
    <!-- /.card-body -->
  </div>
  <!-- /.card -->
</div>
<!-- /.login-box -->
</body>
{% endblock %}

front/templates/mirror_user/recover_password.html
{% extends 'mirror_user/base/mirror_user_base.html' %}


{% block title %}重置密码{% endblock %}

{% block head %}   {% endblock %}


{% block main %}
<body class="hold-transition login-page">
<div class="login-box">
  <div class="card card-outline card-primary">
    <div class="card-header text-center">
      <!--<a href="../../index2.html" class="h1"><b>Mi</b>rror</a>-->
      <img src="{% static 'adminlte/dist/img/logo.png'%}" alt="mirror-logo" height=50px>
    </div>
    <div class="card-body">
      <p class="login-box-msg">只需最后一步即可成功</p>
      <form action="{% url 'mirror_user:user_recoverpassword' %}" method="post">
        {% csrf_token %}
        <div class="input-group mb-3">
          <input type="text" class="form-control" placeholder="用户名" name="username">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-user"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" class="form-control" placeholder="请输入密码" name="password">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" class="form-control" placeholder="再次输入密码" name="confirm">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <button type="submit" class="btn btn-primary btn-block">提交修改</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

      <p class="mt-3 mb-1">
        <a href="{% url 'mirror_user:user_login' %}">前往登录</a>
      </p>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->
</body>
{% endblock %}

front/templates/mirror_user/register.html
{% extends 'mirror_user/base/mirror_user_base.html' %}


{% block title %}注册账户{% endblock %}

{% block head %}   {% endblock %}

{% block main %}
<body class="hold-transition register-page">
<div class="register-box">
  <div class="card card-outline card-primary">
    <div class="card-header text-center">
      <!--<a href="../../index2.html" class="h1"><b>Mi</b>rror</a>-->
      <img src="{% static 'adminlte/dist/img/logo.png'%}" alt="mirror-logo" height=50px>
    </div>
    <div class="card-body">
      <p class="login-box-msg"><font color="#007bff">注册，开启全新旅程</font></p>
      <small>{{form.errors}}</small>

      <form action="{% url 'mirror_user:user_register' %}" method="post">
          {% csrf_token %}
        <div class="input-group mb-3">
          <input type="text" class="form-control" placeholder="用户名" name="username">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-user"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="email" class="form-control" placeholder="邮箱" name="email">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" class="form-control" placeholder="请输入密码" name="password">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" class="form-control" placeholder="再次输入密码" name="confirm">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="id_agree_terms" name="agree_terms" value=1>
              <label for="id_agree_terms">
               我同意 <a href="../register_terms">用户协议</a>
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">注册</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

      <a href="../../mirror_user/login" class="text-center">我有账号，直接登录</a>
    </div>
    <!-- /.form-box -->
  </div><!-- /.card -->
</div>
<!-- /.register-box -->
</body>

{% endblock %}